# Generated by Django 5.2.17 on 2026-09-01 14:29

from django.db import migrations, models


def remap_old_roles(apps, schema_editor):
    """The old three-role scheme (admin/security/it) is replaced by
    admin/saso/security_officer - "it" folds into "admin" (both were
    full-system-control roles under the old scheme; the new brief has no
    separate IT role), and "security" becomes "security_officer" (a rename,
    same real-world job). Any row still holding an old value would otherwise
    just silently fail every role check in accounts/permissions.py."""
    AdminProfile = apps.get_model("accounts", "AdminProfile")
    AdminProfile.objects.filter(role="security").update(role="security_officer")
    AdminProfile.objects.filter(role="it").update(role="admin")


def noop_reverse(apps, schema_editor):
    # Not reversible without knowing which "admin" rows used to be "it" -
    # deliberately a no-op rather than guessing.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='assigned_gate_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(remap_old_roles, noop_reverse),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('saso', 'Security Manager (SASO)'), ('security_officer', 'Security Officer')], max_length=20),
        ),
    ]
