# Generated by Django 5.2.17 on 2026-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_assigned_gate_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
