# Generated by Django 5.2.17 on 2026-10-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminprofile_failed_login_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='staff_card_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
