# Generated by Django 5.2.7 on 2026-07-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=10)),
                ('verification_method', models.CharField(choices=[('nfc_and_face', 'NFC + Face'), ('nfc_only', 'NFC only'), ('manual_override', 'Manual override')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('gate_location', models.CharField(max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_logs', to='users.person')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
