# Generated by Django 5.2.7 on 2026-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='verification_method',
            field=models.CharField(choices=[('nfc_and_face', 'NFC + Face'), ('nfc_only', 'NFC only'), ('face_only', 'Face scan'), ('manual_override', 'Manual override')], max_length=20),
        ),
    ]
