# Generated by Django 5.2.16 on 2026-07-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_entrylog_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='captured_photo',
            field=models.ImageField(blank=True, null=True, upload_to='unenrolled_captures/%Y/%m/%d/'),
        ),
    ]
