# Generated by Django 5.2.16 on 2026-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_entrylog_captured_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='unmatched_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
