# Generated by Django 5.2.16 on 2026-07-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_entrylog_unmatched_encoding'),
        ('users', '0002_faceembedding_delete_faceencoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTiebreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_location', models.CharField(max_length=100, unique=True)),
                ('candidate_person_ids', models.JSONField()),
                ('direction', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrylog',
            name='match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='verification_method',
            field=models.CharField(choices=[('nfc_and_face', 'NFC + Face'), ('nfc_only', 'NFC only'), ('face_only', 'Face scan'), ('manual_override', 'Manual override'), ('face_and_card_tiebreak', 'Face + card tiebreak')], max_length=24),
        ),
        migrations.CreateModel(
            name='RecognitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_location', models.CharField(max_length=100)),
                ('similarity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_attempts', to='users.person')),
            ],
        ),
    ]
