# Generated by Django 5.2.16 on 2026-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_pendingtiebreak_entrylog_match_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_location', models.CharField(max_length=100)),
                ('embedding', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
