# Generated by Django 5.2.17 on 2026-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_liveness_and_spoofattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcclusionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrylog',
            name='occlusion_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('spoof_suspected', 'Spoof suspected'), ('occlusion_detected', 'Occlusion detected')], max_length=20),
        ),
    ]
