# Generated by Django 5.2.17 on 2026-09-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_entrylog_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtiebreak',
            name='reason',
            field=models.CharField(choices=[('ambiguous_match', 'Ambiguous match'), ('confusable_pair', 'Confusable pair')], default='ambiguous_match', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='verification_method',
            field=models.CharField(choices=[('nfc_and_face', 'NFC + Face'), ('nfc_only', 'NFC only'), ('face_only', 'Face scan'), ('manual_override', 'Manual override'), ('face_and_card_tiebreak', 'Face + card tiebreak'), ('confusable_pair_tiebreak', 'Confusable pair tiebreak')], max_length=24),
        ),
    ]
