# Generated by Django 5.2.17 on 2026-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_pendingtiebreak_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtiebreak',
            name='reason',
            field=models.CharField(choices=[('ambiguous_match', 'Ambiguous match'), ('confusable_pair', 'Confusable pair'), ('liveness_unsure', 'Spoof check unsure')], default='ambiguous_match', max_length=20),
        ),
    ]
