# Generated by Django 5.2.17 on 2026-10-08 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_pendingtiebreak_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='on_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_logs_on_duty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='unattended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GateShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_location', models.CharField(db_index=True, max_length=100)),
                ('method', models.CharField(choices=[('password', 'Password'), ('card', 'Staff ID card')], max_length=10)),
                ('signed_in_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('signed_out', 'Signed out'), ('replaced', 'Another guard signed in'), ('gate_closed', 'Gate monitor closed'), ('gate_reopened', 'Gate monitor reopened'), ('expired', 'Shift time limit reached')], max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_in_at'],
            },
        ),
    ]
