# Generated by Django 5.2.17 on 2026-10-09 13:04

from django.core.files.storage import default_storage
from django.db import migrations, models


def delete_exits(apps, schema_editor):
    """The university doesn't record people leaving: delete every exit record
    saved before - successful exits and the unknown / suspected-fake ones from
    exit gates alike - with the gate photos they point at, and any card tap
    an exit gate was still waiting for. (The model's own photo clean-up
    doesn't run inside a migration, so the files are deleted here.)"""
    EntryLog = apps.get_model("logs", "EntryLog")
    PendingTiebreak = apps.get_model("logs", "PendingTiebreak")
    exits = EntryLog.objects.filter(direction="exit")
    photos = {name for name in exits.exclude(captured_photo="").values_list("captured_photo", flat=True) if name}
    exits.delete()
    PendingTiebreak.objects.filter(direction="exit").delete()
    still_used = set(EntryLog.objects.filter(captured_photo__in=photos).values_list("captured_photo", flat=True))
    for name in photos - still_used:
        try:
            default_storage.delete(name)
        except OSError:
            pass  # already gone, or locked - the daily clean-up removes leftovers


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_entrylog_on_duty_entrylog_unattended_gateshift'),
    ]

    operations = [
        # Deleted records can't come back - going back only restores the choice.
        migrations.RunPython(delete_exits, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='entrylog',
            name='direction',
            field=models.CharField(choices=[('entry', 'Entry')], default='entry', max_length=10),
        ),
    ]
