# Generated by Django 5.2.16 on 2026-07-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('source_image', models.ImageField(upload_to='enrollment_photos/%Y/%m/%d/')),
                ('detection_score', models.FloatField(blank=True, null=True)),
                ('is_low_confidence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='users.person')),
            ],
        ),
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
    ]
