# Generated by Django 5.2.16 on 2026-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faceembedding_delete_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceembedding',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to='enrollment_photos/%Y/%m/%d/'),
        ),
    ]
