# Generated by Django 5.2.17 on 2026-09-02 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_deactivationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='distinguishing_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ConfusablePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto_detected', 'Auto-detected at enrollment'), ('manual', 'Manually flagged')], max_length=20)),
                ('detected_similarity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confusable_pairs_flagged', to=settings.AUTH_USER_MODEL)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusable_as_a', to='users.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusable_as_b', to='users.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('person_a', 'person_b'), name='unique_confusable_pair')],
            },
        ),
    ]
