# Generated by Django 5.2.17 on 2026-09-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account_created', 'Account created'), ('account_updated', 'Account updated'), ('account_deactivated', 'Account deactivated'), ('deactivation_requested', 'Deactivation requested'), ('deactivation_approved', 'Deactivation approved'), ('deactivation_rejected', 'Deactivation rejected'), ('manual_override', 'Manual override logged'), ('person_deleted_permanently', 'Person deleted permanently')], max_length=32)),
                ('target_description', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
