# Generated by Django 5.2.17 on 2026-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('account_created', 'Account created'), ('account_updated', 'Account updated'), ('account_deactivated', 'Account deactivated'), ('deactivation_requested', 'Deactivation requested'), ('deactivation_approved', 'Deactivation approved'), ('deactivation_rejected', 'Deactivation rejected'), ('manual_override', 'Manual override logged'), ('person_deleted_permanently', 'Person deleted permanently'), ('confusable_pair_flagged', 'Confusable pair flagged'), ('confusable_pair_removed', 'Confusable pair removed')], max_length=32),
        ),
    ]
