# Generated by Django 5.2.17 on 2026-10-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('account_created', 'Account created'), ('account_updated', 'Account updated'), ('account_deactivated', 'Account deactivated'), ('deactivation_requested', 'Deactivation requested'), ('deactivation_approved', 'Deactivation approved'), ('deactivation_rejected', 'Deactivation rejected'), ('manual_override', 'Manual override logged'), ('person_deleted_permanently', 'Person deleted permanently'), ('confusable_pair_flagged', 'Confusable pair flagged'), ('confusable_pair_removed', 'Confusable pair removed'), ('setting_changed', 'Setting changed'), ('data_purged', 'Old data deleted'), ('data_backed_up', 'Data backed up'), ('account_locked', 'Account locked'), ('gate_sign_in', 'Signed in at a gate'), ('gate_sign_out', 'Signed out of a gate')], max_length=32),
        ),
    ]
